# Generated by Django 5.0.7 on 2024-07-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_is_librarian_user_is_member"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="users_user_uuid_0206f4_idx",
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                error_messages={"unique": "A user with such email already exists."}, max_length=254, unique=True, verbose_name="Email address"
            ),
        ),
    ]
