services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: /start_web
    volumes:
      - .:/app
    ports:
      - 7004:7070
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5433/web_libraryms
    depends_on:
      redis:
        condition: service_started
      db:
        condition: service_healthy

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - PGPORT=5433
      - PGUSER=postgres # also used for pg_isready check below
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: pg_isready
      interval: 1s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: /start_celery_worker
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5433/web_libraryms
    depends_on:
      redis:
        condition: service_started
      db:
        condition: service_healthy

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: /start_celery_beat
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5433/web_libraryms
    depends_on:
      redis:
        condition: service_started
      db:
        condition: service_healthy

  celery_flower:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: /start_celery_flower
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379
      - DATABASE_URL=postgres://postgres:postgres@db:5433/web_libraryms
    ports:
      - 5557:5555
    depends_on:
      redis:
        condition: service_started
      db:
        condition: service_healthy


volumes:
  postgres-data:
