services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: /start_web
    volumes:
      - .:/app
    ports:
      - 7004:7070
    env_file: .env.docker.dev
    depends_on:
      db:
        condition: service_healthy

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file: .env.docker.dev
    healthcheck:
      test: pg_isready
      interval: 1s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: /start_celery_worker
    volumes:
      - .:/app
    env_file: .env.docker.dev
    depends_on:
      redis:
        condition: service_started
      db:
        condition: service_healthy

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: /start_celery_beat
    volumes:
      - .:/app
    env_file: .env.docker.dev
    depends_on:
      redis:
        condition: service_started
      db:
        condition: service_healthy

volumes:
  postgres-data:
