# fly.toml app configuration file generated for django-libraryms on 2024-08-08T15:59:36+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'django-libraryms'
primary_region = 'waw'

[build]

[deploy]
  release_command = 'python src/manage.py migrate'

[processes]
  app = "python -m gunicorn --bind :8000 --chdir src --workers 2 core.wsgi:application"
  # worker = "python -m celery --app core --workdir src worker --loglevel=info"
  # beat = "python -m celery --app core --workdir src beat --loglevel=info --pidfile= --scheduler django_celery_beat.schedulers:DatabaseScheduler"

[env]
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = "suspend"
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512'
  cpu_kind = 'shared'
  cpus = 1


[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/healthz"

