# Generated by Django 5.0.7 on 2024-07-12 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("year_of_birth", models.PositiveSmallIntegerField(null=True)),
                ("year_of_death", models.PositiveSmallIntegerField(null=True)),
            ],
            options={
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("title", models.CharField(max_length=200, unique=True)),
                (
                    "language",
                    models.CharField(
                        choices=[("lv", "Latvian"), ("en", "English"), ("ru", "Russian"), ("de", "German"), ("es", "Spanish"), ("fr", "French")], max_length=2
                    ),
                ),
                ("published_at", models.PositiveSmallIntegerField(verbose_name="Year of publishing")),
                ("pages", models.PositiveSmallIntegerField(verbose_name="Number of pages")),
                ("pages_description", models.CharField(max_length=100, null=True, verbose_name="Extra description for pages")),
                ("isbn", models.CharField(max_length=13, verbose_name="ISBN")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Publisher",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("city", models.CharField(max_length=100, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="author",
            constraint=models.UniqueConstraint(fields=("first_name", "last_name"), name="unique_author_name"),
        ),
        migrations.AddField(
            model_name="book",
            name="author",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="books.author"),
        ),
        migrations.AddField(
            model_name="book",
            name="publisher",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="books.publisher"),
        ),
    ]
