# Generated by Django 5.0.7 on 2024-07-15 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
        ("users", "0002_user_is_librarian_user_is_member"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"ordering": ["-modified_at"]},
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("U", "Unprocessed"), ("R", "Refused"), ("Q", "In Queue"), ("MC", "Member Cancelled"), ("P", "Processed")],
                        default="U",
                        max_length=2,
                    ),
                ),
                ("book", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="books.book")),
                ("member", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="users.member")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("R", "Reserved"), ("I", "Issued"), ("C", "Completed"), ("RF", "Refused"), ("X", "Cancelled")], default="R", max_length=2
                    ),
                ),
                ("term", models.DateTimeField(default=None, null=True, verbose_name="Date, when book should be returned back")),
                ("member", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="users.member")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="book",
            name="reservation",
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="books.reservation"),
        ),
    ]
