# Generated by Django 5.0.7 on 2024-07-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_add_book_reservation_order_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="term",
            field=models.DateField(blank=True, default=None, help_text="Date when reservation expires, 14 days by default", null=True, verbose_name="Due date"),
        ),
    ]
