# Generated by Django 5.0.7 on 2024-07-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0004_order_change_reason_order_last_modified_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="cover",
            field=models.ImageField(blank=True, help_text="The cover image of book", upload_to="books/covers/", verbose_name="Cover image"),
        ),
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(max_length=13, unique=True, verbose_name="ISBN"),
        ),
    ]
