# Generated by Django 5.0.7 on 2024-07-26 07:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0005_book_cover_alter_book_isbn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="year_of_birth",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="author",
            name="year_of_death",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
