# Generated by Django 5.0.7 on 2024-07-26 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0006_alter_author_year_of_birth_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalorder",
            name="reservation",
            field=models.ForeignKey(
                blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name="+", to="books.reservation"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="reservation",
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="books.reservation"),
        ),
    ]
