# Generated by Django 5.0.7 on 2024-08-05 15:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0008_alter_book_pages_description_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reservation",
            options={"ordering": ["-modified_at"]},
        ),
    ]
