# Generated by Django 5.0.7 on 2024-08-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0009_alter_reservation_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalorder",
            name="member_notified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="member_notified",
            field=models.BooleanField(default=False),
        ),
    ]
