# Generated by Django 5.0.7 on 2024-08-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0010_historicalorder_member_notified_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reservation",
            options={"ordering": [models.OrderBy(models.F("modified_at"), descending=True, nulls_last=True)]},
        ),
    ]
