# Generated by Django 5.0.7 on 2024-08-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0012_alter_author_year_of_birth_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"ordering": [models.OrderBy(models.F("modified_at"), descending=True, nulls_last=True)]},
        ),
    ]
