# Generated by Django 5.0.8 on 2024-08-24 15:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial_squashed_0013_alter_book_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalorder",
            name="member_notified",
        ),
        migrations.RemoveField(
            model_name="order",
            name="member_notified",
        ),
    ]
