# Generated by Django 5.0.8 on 2024-08-26 14:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0014_remove_order_member_notified"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reservation",
            options={"ordering": ["-created_at"]},
        ),
    ]
