# Generated by Django 5.1.1 on 2025-03-16 07:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0016_alter_reservation_term_reservationextension"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="year_of_birth",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2025, message="Year of birth cannot be greater than current year")]
            ),
        ),
        migrations.AlterField(
            model_name="author",
            name="year_of_death",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2025, message="Year of birth cannot be greater than current year")]
            ),
        ),
    ]
