name: CI/CD

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '.tool-versions'
      - '.gitignore'
      - '.dockerignore'
      - 'demo/**'
  pull_request:


env:
  CI: true
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_CONTEXT: ${{ toJson(github) }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: build
        uses: ./.github/actions/build

      - name: lint
        run: make lint -e RUN_MAKEMIGRATIONS=1

  test:
    needs: lint
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: test_web_libraryms
          POSTGRES_PASSWORD: postgres
          PGUSER: postgres # default for healthcheck
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: build
        uses: ./.github/actions/build

      - name: test
        run: make test

  deploy:
    if: github.ref == 'refs/heads/main' && github.repository_owner == 'peacefulseeker'
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to render
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"
